
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxnykapuafqllixquakc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4bnlrYXB1YWZxbGxpeHF1YWtjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzAyOTIsImV4cCI6MjA1NzQwNjI5Mn0.HPlTH3nRRpFKme2vXGwJIKX0My3ENOo10fIbGh-1tpY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

/**
 * Delete a user from the Supabase Auth system using Edge Function
 * This function calls the delete-user edge function
 * @param userId The ID of the user to delete
 */
export const deleteUserFromAuth = async (userId: string) => {
  try {
    console.log("Calling delete-user edge function for user ID:", userId);
    
    const { data, error } = await supabase.functions.invoke('delete-user', {
      body: { userId },
    });
    
    if (error) {
      console.error("Error calling delete-user function:", error);
      throw error;
    }
    
    console.log("Successfully deleted user from auth system:", data);
    return data;
  } catch (error) {
    console.error("Error in deleteUserFromAuth:", error);
    throw error;
  }
};
